---
name: test
on: [push, pull_request]

jobs:
    docker:
        runs-on: ubuntu-20.04
        name: Docker
        steps:
            - uses: actions/checkout@v2
            - name: docker build
              run: docker build . -t metacpan/metacpan-web:latest
            - name: run Perl tests
              run: docker run -i metacpan/metacpan-web carton exec prove -lr --jobs 2 t
            - name: push build to Docker hub
              run: >
                  echo "${{ secrets.DOCKER_HUB_TOKEN }}" |
                  docker login
                  -u ${{ secrets.DOCKER_HUB_USER }}
                  --password-stdin
                  && docker push metacpan/metacpan-web:latest
              if: success() && github.ref == 'refs/heads/master'
    test:
        runs-on: ubuntu-20.04
        name: Dockerless
        strategy:
            fail-fast: false
            matrix:
                perl-version:
                    - "5.30"
                resolver:
                    - metacpan
                    - snapshot
        container:
            image: perl:${{ matrix.perl-version }}
            env:
                DEVEL_COVER_OPTIONS: "-ignore,^local/"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "10"
            - run: npm install -g yarn && yarn install
            - name: Install Carton
              run: >
                  curl -sL https://git.io/cpm | perl -
                  install -g Carton
                  --show-build-log-on-failure
            - name: Install deps
              run: >
                  curl -sL https://git.io/cpm | perl -
                  install
                  --cpanfile cpanfile
                  --resolver ${{ matrix.resolver }}
                  --show-build-log-on-failure
                  --local-lib-contained=local
              if: success()
            - name: Maybe update cpanfile.snapshot
              run: carton
              if: success()
            - name: Run Tests
              run: carton exec prove -lr --jobs 2 t
              if: success()
              env:
                  TEST_TIDYALL_VERBOSE: 1
            - uses: actions/upload-artifact@v2
              with:
                  name: "${{ matrix.perl-version }}.${{ matrix.resolver }}"
                  path: cpanfile.snapshot
              if: success() && matrix.resolver == 'metacpan'
